procedure_test: False

# main visual parameters
screen_color: grey
text_color: black
text_size: 28

stimulus_dist: 60
stimulus_size: 53
stimulus_color: black
stimulus_central_pos: [0, 0]

stimulus_border_color: green
stimulus_border_width: 6

# stimulus
stimulus_type: image
stimulus_list: ["g1.png", "g2.png", "g3.png", "g4.png", "g5.png", "g6.png", "g7.png", "g8.png", "g9.png"]
              # [10_2.png, 17_2.png, 18_2.png, 20_2.png, 21_2.png, 22_2.png, 23_2.png, 24_2.png, 25_2.png]

# reactions

# time parameters
matrix_1_time: 2
mask_time: 1
matrix_2_time: 4

# training
do_training: True
fdbk_training: True
training_randomize: False
training_trials: [{n_trials: 6, n_elements: 6, size: [3, 3], group_elements: True}]


# experiment
fdbk_experiment: False
experiment_randomize: False
experiment_trials: [{n_trials: 100, n_elements: 6, size: [3, 3], group_elements: True}]

# break
show_break_after_n_trials: 50

# fixation point
fixation_size: 56
fixation_color: black
fixation_text: +
fixation_time: 2
fixation_pos: [0, 0]

# mask
extra_mask_size: 0
mask_pos: [0, 0]

# recall
recall_size: 56
recall_color: red
recall_text: •
recall_time_start: -1 # From the beginning of matrix_1
recall_time_end: -1 # From the beginning of matrix_1


# feedback
fdbk_correct: Poprawna odpowiedź
fdbk_incorrect: Błędna odpowiedź
fdbk_no_answer: Brak odpowiedzi
fdbk_show_time: 2
fdbk_color: black
fdbk_size: 30

# wait
wait_time: 1.5
wait_jitter: 1


# show extra text during trial
extra_text_to_show: []
                       # [{pos: [-270, -250], color: black, size: 40, text: "wprowadź odpowiedź:"},
                       #  {pos: [450, -350], color: black, size: 30, text: "zatwierdź enter"}]

# clock
show_clock: false
clock_pos: [450, 350]
clock_size: 60
clock_show_time: 7

# timer
show_timer: false
timer_pos: [600, 350]
timer_color: black
timer_size: 60